const initialDocs=[
 {id:'insurance',name:'Renters Insurance Policy.pdf',detail:'Added Sep 18, 2026 · 4 pages',category:'Home',date:'Sep 18, 2026',status:'Action soon',statusType:'attention',icon:'PDF',iconType:'pdf',title:'Your insurance is up for renewal',intro:'Your renters insurance policy ends on October 4. You have time to compare your options before it renews.',quote:'“This policy expires at 11:59 p.m. on October 4, 2026. Renewal is subject to the premium shown in your renewal notice.”',next:'Check your renewal price against other providers. We can help you make a short comparison checklist.'},
 {id:'streamly',name:'Streamly monthly receipt.pdf',detail:'Added Sep 27, 2026 · 1 page',category:'Money',date:'Sep 27, 2026',status:'Price changed',statusType:'note',icon:'PDF',iconType:'pdf',title:'A subscription price changed',intro:'Your Streamly plan is increasing from £8.99 to £10.99 per month starting with your next billing cycle.',quote:'“Your subscription price will change to £10.99/month on October 11, 2026.”',next:'Decide whether you want to keep the plan at the new price. Your account settings show how to cancel before October 11.'},
 {id:'appointment',name:'Appointment summary — Dr. Lee.pdf',detail:'Added Sep 24, 2026 · 2 pages',category:'Health',date:'Sep 24, 2026',status:'Summary ready',statusType:'ready',icon:'PDF',iconType:'pdf',title:'Your appointment summary',intro:'We found the follow-up instructions in your visit summary. Here are the key points for your records.',quote:'“Continue current treatment. Book a follow-up appointment in approximately six weeks if symptoms persist.”',next:'Keep this summary with your health records. If you have questions about your care, contact your healthcare provider.'},
 {id:'energy',name:'Bright Energy — September bill.pdf',detail:'Added Sep 22, 2026 · 3 pages',category:'Home',date:'Sep 22, 2026',status:'No action needed',statusType:'ready',icon:'PDF',iconType:'pdf'},
 {id:'payslip',name:'September payslip.pdf',detail:'Added Sep 20, 2026 · 1 page',category:'Work',date:'Sep 20, 2026',status:'For your records',statusType:'ready',icon:'PDF',iconType:'pdf'},
 {id:'council',name:'Council tax 2026–27.pdf',detail:'Added Sep 19, 2026 · 2 pages',category:'Home',date:'Sep 19, 2026',status:'Due Nov 1',statusType:'attention',icon:'PDF',iconType:'pdf'}
];
let docs=JSON.parse(localStorage.getItem('papertrail-docs')||'null')||initialDocs;let activeFilter='All';let currentDoc=null;let toastTimer;const chatByDocument=new Map();
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
// Documents stay in this browser's private IndexedDB. GitHub Pages has no private server.
let paperDB;
const extractedByDocument=new Map();
function openPaperDB(){return new Promise((resolve,reject)=>{if(!('indexedDB'in window))return reject(new Error('This browser cannot save documents privately.'));const request=indexedDB.open('papertrail-private-documents',1);request.onupgradeneeded=()=>request.result.createObjectStore('documents',{keyPath:'id'});request.onsuccess=()=>{paperDB=request.result;resolve(paperDB)};request.onerror=()=>reject(request.error)})}
function savePrivateDocument(record){return new Promise((resolve,reject)=>{const tx=paperDB.transaction('documents','readwrite');tx.objectStore('documents').put(record);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})}
function loadPrivateDocument(id){return new Promise((resolve,reject)=>{const req=paperDB.transaction('documents').objectStore('documents').get(id);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
async function extractFile(file){const ext=file.name.split('.').pop().toLowerCase();if(ext==='txt')return [{page:1,text:await file.text()}];if(ext==='pdf'){const pdfjs=await import('https://cdn.jsdelivr.net/npm/pdfjs-dist@4.10.38/build/pdf.min.mjs');pdfjs.GlobalWorkerOptions.workerSrc='https://cdn.jsdelivr.net/npm/pdfjs-dist@4.10.38/build/pdf.worker.min.mjs';const pdf=await pdfjs.getDocument({data:new Uint8Array(await file.arrayBuffer())}).promise;const pages=[];for(let n=1;n<=pdf.numPages;n++){const content=await (await pdf.getPage(n)).getTextContent();pages.push({page:n,text:content.items.map(item=>item.str).join(' ').replace(/\s+/g,' ').trim()})}if(!pages.some(p=>p.text))throw new Error('This PDF has no selectable text. Scanned page reading needs OCR, which is not connected yet.');return pages}throw new Error(ext==='docx'?'Word document reading is not connected yet. Please export it as a PDF or text file.':'Image reading needs OCR, which is not connected yet.')}
function findDates(text){const out=[];const rx=/\b(?:\d{1,2}(?:st|nd|rd|th)?\s+(?:January|February|March|April|May|June|July|August|September|October|November|December)|(?:January|February|March|April|May|June|July|August|September|October|November|December)\s+\d{1,2}(?:st|nd|rd|th)?)(?:,?\s+20\d{2})?\b|\b\d{1,2}[/.]\d{1,2}[/.]20\d{2}\b/gi;let m;while((m=rx.exec(text))&&out.length<12)out.push(m[0]);return [...new Set(out)]}
function notifyDueReminders(){if(!('Notification'in window)||Notification.permission!=='granted')return;const reminders=JSON.parse(localStorage.getItem('papertrail-reminders')||'[]'),now=Date.now();let changed=false;for(const reminder of reminders){if(!reminder.notified&&new Date(reminder.due).getTime()-86400000<=now){new Notification('Papertrail reminder',{body:`Check ${reminder.name}: ${reminder.dateText}`});reminder.notified=true;changed=true}}if(changed)localStorage.setItem('papertrail-reminders',JSON.stringify(reminders))}
function storeReminder(dateText){const numeric=dateText.match(/^(\d{1,2})[/.](\d{1,2})[/.](20\d{2})$/);let due;if(numeric){due=new Date(Number(numeric[3]),Number(numeric[2])-1,Number(numeric[1]),9)}else{const months={january:0,february:1,march:2,april:3,may:4,june:5,july:6,august:7,september:8,october:9,november:10,december:11},m=dateText.match(/(\d{1,2})(?:st|nd|rd|th)?\s+(January|February|March|April|May|June|July|August|September|October|November|December)|(January|February|March|April|May|June|July|August|September|October|November|December)\s+(\d{1,2})(?:st|nd|rd|th)?(?:,?\s+(20\d{2}))?/i);if(!m)return;const month=months[(m[2]||m[3]).toLowerCase()],day=Number(m[1]||m[4]),year=Number(m[5]||new Date().getFullYear());due=new Date(year,month,day,9);if(!m[5]&&due<new Date())due.setFullYear(due.getFullYear()+1)}const reminders=JSON.parse(localStorage.getItem('papertrail-reminders')||'[]');if(!reminders.some(r=>r.documentId===currentDoc.id&&r.due===due.toISOString()))reminders.push({id:crypto.randomUUID?.()||String(Date.now()),documentId:currentDoc.id,name:currentDoc.name,dateText,due:due.toISOString(),created:new Date().toISOString()});localStorage.setItem('papertrail-reminders',JSON.stringify(reminders));const doc=docs.find(item=>item.id===currentDoc.id);if(doc){doc.status='Reminder set';doc.statusType='attention';store();render()}notifyDueReminders();showToast('Reminder saved on this device. Open Papertrail near the date to be notified.');$('#date-reminder-action').textContent='Reminder saved on this device.'}
function sourceSentences(doc){const pages=extractedByDocument.get(doc.id)||[];return pages.flatMap(p=>p.text.split(/(?<=[.!?])\s+/).filter(Boolean).map(text=>({text,page:p.page}))) }
function findEvidence(question,doc){const q=question.toLowerCase(),terms=q.replace(/[^a-z0-9£$]+/g,' ').split(/\s+/).filter(w=>w.length>2&&!['what','when','where','which','does','this','that','with','from','about','have','should','could','would','tell','show','document'].includes(w));const sentences=sourceSentences(doc);const scored=sentences.map(s=>({...s,score:terms.reduce((n,t)=>n+(s.text.toLowerCase().includes(t)?1:0),0)})).filter(s=>s.score>0).sort((a,b)=>b.score-a.score);return scored.slice(0,3)}
function store(){localStorage.setItem('papertrail-docs',JSON.stringify(docs));$('#doc-count').textContent=docs.length}
function row(d){return `<div class="doc-row" data-open="${d.id}"><div class="doc-name"><span class="file-icon ${d.iconType||'pdf'}">${d.icon||'PDF'}</span><span class="doc-copy"><strong>${escapeHtml(d.name)}</strong><small>${escapeHtml(d.detail||'Added just now')}</small></span></div><span class="doc-category">${escapeHtml(d.category||'Other')}</span><span class="doc-date">${escapeHtml(d.date||'Today')}</span><span class="doc-status status-${d.statusType||'ready'}">${escapeHtml(d.status||'Added')}</span><span class="row-more">···</span></div>`}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function render(){const list=docs.slice(0,5);$('#document-list').innerHTML=list.length?list.map(row).join(''):'<div class="empty-state">No documents here yet. Add one to get started.</div>';let filtered=activeFilter==='All'?docs:docs.filter(d=>d.category===activeFilter);$('#alternate-list').innerHTML=filtered.length?filtered.map(row).join(''):'<div class="empty-state">No documents in this category yet.</div>';$('#todo-count').textContent=docs.filter(d=>d.statusType==='attention').length;$('#todo-total').textContent=docs.filter(d=>d.statusType==='attention').length;$('#doc-count').textContent=docs.length}
function showToast(msg){let t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),2600)}
function openDoc(id){let d=docs.find(x=>x.id===id)||initialDocs.find(x=>x.id===id);if(!d){showToast('This document is saved in your space.');return}currentDoc=d;$('#date-reminder-action').replaceChildren();$('#modal-title').textContent=d.title||d.name;$('#modal-intro').textContent=d.intro||'This document has been added to your Papertrail space. We’ll help surface the important details and dates.';$('#source-name').textContent=d.name;$('#source-quote').textContent=d.quote||'Papertrail has saved this document. Add a connected AI service to extract verified details and reminders.';$('#source-status').textContent=d.uploaded?'Saved on this device':'Sample detail';$('#modal-next-text').textContent=d.next||'Open the document and review it when you have a moment.';$('#modal-category').textContent=`${d.category||'DOCUMENT'} · PAPERTRAIL FOUND THIS`;$('#chat-panel').classList.add('hidden');$('.detail-modal').classList.remove('chat-active');$('#ask-question').textContent='Ask Papertrail';renderChat();$('#modal-backdrop').classList.remove('hidden');if(d.uploaded)loadPrivateDocument(id).then(record=>{if(!record||currentDoc?.id!==id)return;extractedByDocument.set(id,record.pages||[]);const dates=record.dates||findDates((record.pages||[]).map(p=>p.text).join(' '));$('#modal-intro').textContent=record.pages?.some(p=>p.text)?`Text extracted from ${record.pages.length} page${record.pages.length===1?'':'s'} on this device. Ask a question to find exact details.`:record.error||'No readable text was found in this file.';$('#source-quote').textContent=dates.length?`Dates found: ${dates.join(', ')}`:`${record.pages?.length||0} page${record.pages?.length===1?'':'s'} of text available for questions.`;$('#modal-category').textContent='DOCUMENT · PROCESSED ON THIS DEVICE';$('#modal-next-text').textContent=dates.length?`Dates to check in the original file: ${dates.join(', ')}.`:'Ask Papertrail about a detail in this document.';if(dates.length){const button=document.createElement('button');button.className='text-link';button.textContent='Remind me about the first date';button.onclick=()=>{if('Notification'in window&&Notification.permission==='default')Notification.requestPermission().finally(()=>storeReminder(dates[0]));else storeReminder(dates[0])};$('#date-reminder-action').append(button)}renderChat()}).catch(()=>showToast('Could not open the saved document.'))}
function renderChat(){const messages=chatByDocument.get(currentDoc?.id)||[];const box=$('#chat-messages');box.innerHTML='';messages.forEach(message=>{const item=document.createElement('div');item.className=`chat-message ${message.role}`;const label=document.createElement('b');label.textContent=message.role==='assistant'?'Papertrail':'You';const text=document.createElement('p');text.textContent=message.text;item.append(label,text);if(message.role==='assistant'&&message.source){const source=document.createElement('small');source.className='chat-source';source.textContent=`From ${message.source}`;item.append(source)}box.append(item)});box.scrollTop=box.scrollHeight}
function addChatMessage(role,text,source=''){if(!currentDoc)return;const messages=chatByDocument.get(currentDoc.id)||[];messages.push({role,text,source});chatByDocument.set(currentDoc.id,messages);renderChat()}
function answerFromDocument(question){const doc=currentDoc;const pages=extractedByDocument.get(doc.id)||[];if(pages.length){const evidence=findEvidence(question,doc);if(!evidence.length)return `I couldn't find an answer in the readable text of this document. Try different words, or check the original file. No answer has been guessed.`;return evidence.map(item=>`“${item.text}” (page ${item.page})`).join('\n\n')}const q=question.toLowerCase();const hasDetails=Boolean(doc.intro||doc.quote||doc.next);if(!hasDetails)return `I can’t find that detail in the saved notes for ${doc.name}. You can still check the original document for the answer.`;if(/\b(when|date|due|deadline|expire|expires|renew|renewal)\b/.test(q))return doc.quote&&/\b(date|expire|renew|due|october|november|\d{1,2})\b/i.test(doc.quote)?`Here’s the date information I found: ${doc.quote}`:`The saved notes say: ${doc.intro}`;if(/\b(cost|price|amount|pay|£|\$|fee|bill|charge)\b/.test(q))return /£|\$|\b\d/.test(`${doc.intro} ${doc.quote}`)?`Here’s the amount information I found: ${doc.intro}`:`I don’t see an amount in the saved notes for this document.`;if(/\b(next|should|do|action|handle|start|step)\b/.test(q))return doc.next||`The saved notes say: ${doc.intro}`;if(/\b(summary|main|know|about|explain|mean)\b/.test(q))return `${doc.intro}${doc.quote?`\n\nKey detail: ${doc.quote}`:''}`;return `I can help with the main point, important dates, amounts, or what to do next. From the saved notes: ${doc.intro}`}
function askDocument(question){const q=question.trim();if(!q||!currentDoc)return;addChatMessage('user',q);addChatMessage('assistant',answerFromDocument(q),currentDoc.uploaded?'Pages in your document':currentDoc.name)}
function setView(view){const overview=view==='overview',profile=view==='profile';$('#overview-page').classList.toggle('hidden',!overview);$('#alternate-page').classList.toggle('hidden',overview||profile);$('#profile-page').classList.toggle('hidden',!profile);$$('.nav-item,.mobile-nav-item,.profile[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$('#crumb').textContent=overview?'Home':profile?'Your profile':view==='actions'?'To-dos':'Documents';if(!overview&&!profile){const actions=view==='actions';$('#alternate-title').textContent=actions?'To-dos':'Documents';$('#alternate-lede').textContent=actions?'Things to take care of, in one simple list.':'All your important files, together in one place.';$$('.alt-filters').forEach(e=>e.classList.toggle('hidden',actions));$('#alternate-list').innerHTML=actions?docs.filter(d=>d.statusType==='attention').map(row).join('')||'<div class="empty-state">You’re all caught up. Nice work.</div>':$('#alternate-list').innerHTML}window.scrollTo({top:0,behavior:'smooth'})}
document.addEventListener('click',e=>{const nav=e.target.closest('[data-view]');if(nav)setView(nav.dataset.view);const link=e.target.closest('[data-view-link]');if(link)setView(link.dataset.viewLink);const open=e.target.closest('[data-open]');if(open)openDoc(open.dataset.open);const cat=e.target.closest('[data-category]');if(cat){activeFilter=cat.dataset.category;setView('inbox');$$('.filter-chip').forEach(b=>b.classList.toggle('selected',b.dataset.filter===activeFilter));render()}const filter=e.target.closest('[data-filter]');if(filter){activeFilter=filter.dataset.filter;$$('.filter-chip').forEach(b=>b.classList.toggle('selected',b===filter));render()}});
$('#upload-btn').onclick=()=>$('#file-input').click();$('#upload-btn-alt').onclick=()=>$('#file-input').click();$('#file-input').addEventListener('change',async e=>{const files=[...e.target.files];if(!files.length)return;try{await openPaperDB()}catch{showToast('Private document storage is unavailable in this browser.');e.target.value='';return}for(const f of files){const ext=f.name.split('.').pop().toLowerCase(),id='upload-'+Date.now()+Math.random().toString(16).slice(2),doc={id,name:f.name,detail:`Added just now · ${Math.max(1,Math.round(f.size/1024))} KB`,category:'Other',date:'Today',status:'Reading document…',statusType:'note',icon:ext==='pdf'?'PDF':ext.toUpperCase().slice(0,3),iconType:['jpg','jpeg','png'].includes(ext)?'image':'pdf',uploaded:true};docs.unshift(doc);store();render();try{const pages=await extractFile(f);extractedByDocument.set(id,pages);const text=pages.map(p=>p.text).join(' '),dates=findDates(text);await savePrivateDocument({id,file:f,pages,dates,savedAt:new Date().toISOString()});doc.status=dates.length?`${dates.length} date${dates.length===1?'':'s'} found`:'Text ready';doc.statusType=dates.length?'attention':'ready';doc.detail=`Added just now · ${pages.length} page${pages.length===1?'':'s'} · processed on this device`;doc.dates=dates;store()}catch(error){doc.status='Could not read';doc.statusType='attention';doc.error=error.message;try{await savePrivateDocument({id,file:f,pages:[],error:error.message,savedAt:new Date().toISOString()})}catch{}store()}render()}showToast(`${files.length} document${files.length===1?'':'s'} saved privately on this device`);e.target.value=''});
$('#mobile-add').onclick=()=>$('#file-input').click();
const savedProfile=JSON.parse(localStorage.getItem('papertrail-profile')||'{}');
function showProfileName(name){$$('.profile-name').forEach(el=>el.textContent=name);$$('.profile-avatar,.profile-avatar-large').forEach(el=>el.textContent=name.trim().split(/\s+/).map(part=>part[0]).join('').slice(0,2).toUpperCase());const greeting=$('#overview-page h1');if(greeting)greeting.innerHTML=`Good morning, ${escapeHtml(name.split(/\s+/)[0])}<span class="wave">✳</span>`}
$('#profile-name-input').value=savedProfile.name||'Naomi Davis';$('#profile-email-input').value=savedProfile.email||'naomi@example.com';showProfileName($('#profile-name-input').value);
$('#profile-form').addEventListener('submit',e=>{e.preventDefault();const name=$('#profile-name-input').value.trim(),email=$('#profile-email-input').value.trim();if(!name||!email)return;localStorage.setItem('papertrail-profile',JSON.stringify({name,email}));showProfileName(name);showToast('Your profile has been saved.')});
['date-reminders','document-updates'].forEach(id=>{const input=$(`#${id}`);input.checked=localStorage.getItem(`papertrail-${id}`)!=='false';input.addEventListener('change',()=>{localStorage.setItem(`papertrail-${id}`,input.checked);showToast('Reminder settings saved.')})});
$('#modal-close').onclick=()=>$('#modal-backdrop').classList.add('hidden');$('#modal-backdrop').addEventListener('click',e=>{if(e.target.id==='modal-backdrop')e.currentTarget.classList.add('hidden')});document.addEventListener('keydown',e=>{if(e.key==='Escape')$('#modal-backdrop').classList.add('hidden')});$('#mark-done').onclick=()=>{if(currentDoc){const d=docs.find(x=>x.id===currentDoc.id);if(d){d.status='Handled';d.statusType='ready';store();render()}$('#modal-backdrop').classList.add('hidden');showToast('Marked as handled. One less thing to think about.')}};$('#ask-question').onclick=()=>{const opening=$('#chat-panel').classList.contains('hidden');$('#chat-panel').classList.toggle('hidden',!opening);$('.detail-modal').classList.toggle('chat-active',opening);$('#ask-question').textContent=opening?'Close chat':'Ask Papertrail';if(opening&&!(chatByDocument.get(currentDoc.id)||[]).length){addChatMessage('assistant',`Hi! Ask me about ${currentDoc.title||currentDoc.name}. I can help with details in the saved notes.` ,currentDoc.name)}if(opening)$('#chat-input').focus()};$('#chat-close').onclick=()=>{$('#chat-panel').classList.add('hidden');$('.detail-modal').classList.remove('chat-active');$('#ask-question').textContent='Ask Papertrail'};$('#chat-form').addEventListener('submit',e=>{e.preventDefault();const input=$('#chat-input');askDocument(input.value);input.value='';input.focus()});$('#chat-prompts').addEventListener('click',e=>{const prompt=e.target.closest('[data-chat-prompt]');if(prompt)askDocument(prompt.dataset.chatPrompt)});$('#help-btn').onclick=()=>showToast('Tell us what’s on your mind at hello@papertrail.app');$('#upgrade-btn').onclick=()=>showToast('Papertrail Plus is coming soon.');$('#filter-button').onclick=()=>setView('inbox');$('#search-open').onclick=()=>{const q=prompt('Search your documents');if(q!==null){setView('inbox');activeFilter='All';render();const matches=docs.filter(d=>d.name.toLowerCase().includes(q.toLowerCase()));$('#alternate-list').innerHTML=matches.length?matches.map(row).join(''):`<div class="empty-state">No documents found for “${escapeHtml(q)}”.</div>`}};
window.addEventListener('focus',notifyDueReminders);document.addEventListener('visibilitychange',()=>{if(!document.hidden)notifyDueReminders()});
render();
openPaperDB().then(db=>{const req=db.transaction('documents').objectStore('documents').getAll();req.onsuccess=()=>{for(const record of req.result){const doc=docs.find(item=>item.id===record.id);if(!doc)continue;if(record.pages?.length){extractedByDocument.set(doc.id,record.pages);doc.dates=record.dates||findDates(record.pages.map(p=>p.text).join(' '));doc.status=doc.dates.length?`${doc.dates.length} date${doc.dates.length===1?'':'s'} found`:'Text ready';doc.statusType=doc.dates.length?'attention':'ready'}else if(record.error){doc.status='Could not read';doc.statusType='attention';doc.error=record.error}}store();render()}}).catch(()=>{});
if('serviceWorker' in navigator && (location.protocol==='https:'||location.hostname==='localhost'))navigator.serviceWorker.register('./service-worker.js').catch(()=>{});
