const initialDocs=[
 {id:'insurance',name:'Renters Insurance Policy.pdf',detail:'Added Sep 18, 2026 · 4 pages',category:'Home',date:'Sep 18, 2026',status:'Action soon',statusType:'attention',icon:'PDF',iconType:'pdf',title:'Your insurance is up for renewal',intro:'Your renters insurance policy ends on October 4. You have time to compare your options before it renews.',quote:'“This policy expires at 11:59 p.m. on October 4, 2026. Renewal is subject to the premium shown in your renewal notice.”',next:'Check your renewal price against other providers. We can help you make a short comparison checklist.'},
 {id:'streamly',name:'Streamly monthly receipt.pdf',detail:'Added Sep 27, 2026 · 1 page',category:'Money',date:'Sep 27, 2026',status:'Price changed',statusType:'note',icon:'PDF',iconType:'pdf',title:'A subscription price changed',intro:'Your Streamly plan is increasing from £8.99 to £10.99 per month starting with your next billing cycle.',quote:'“Your subscription price will change to £10.99/month on October 11, 2026.”',next:'Decide whether you want to keep the plan at the new price. Your account settings show how to cancel before October 11.'},
 {id:'appointment',name:'Appointment summary — Dr. Lee.pdf',detail:'Added Sep 24, 2026 · 2 pages',category:'Health',date:'Sep 24, 2026',status:'Summary ready',statusType:'ready',icon:'PDF',iconType:'pdf',title:'Your appointment summary',intro:'We found the follow-up instructions in your visit summary. Here are the key points for your records.',quote:'“Continue current treatment. Book a follow-up appointment in approximately six weeks if symptoms persist.”',next:'Keep this summary with your health records. If you have questions about your care, contact your healthcare provider.'},
 {id:'energy',name:'Bright Energy — September bill.pdf',detail:'Added Sep 22, 2026 · 3 pages',category:'Home',date:'Sep 22, 2026',status:'No action needed',statusType:'ready',icon:'PDF',iconType:'pdf'},
 {id:'payslip',name:'September payslip.pdf',detail:'Added Sep 20, 2026 · 1 page',category:'Work',date:'Sep 20, 2026',status:'For your records',statusType:'ready',icon:'PDF',iconType:'pdf'},
 {id:'council',name:'Council tax 2026–27.pdf',detail:'Added Sep 19, 2026 · 2 pages',category:'Home',date:'Sep 19, 2026',status:'Due Nov 1',statusType:'attention',icon:'PDF',iconType:'pdf'}
];
let docs=JSON.parse(localStorage.getItem('papertrail-docs')||'null')||initialDocs;let activeFilter='All';let currentDoc=null;let toastTimer;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function store(){localStorage.setItem('papertrail-docs',JSON.stringify(docs));$('#doc-count').textContent=docs.length}
function row(d){return `<div class="doc-row" data-open="${d.id}"><div class="doc-name"><span class="file-icon ${d.iconType||'pdf'}">${d.icon||'PDF'}</span><span class="doc-copy"><strong>${escapeHtml(d.name)}</strong><small>${escapeHtml(d.detail||'Added just now')}</small></span></div><span class="doc-category">${escapeHtml(d.category||'Other')}</span><span class="doc-date">${escapeHtml(d.date||'Today')}</span><span class="doc-status status-${d.statusType||'ready'}">${escapeHtml(d.status||'Added')}</span><span class="row-more">···</span></div>`}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function render(){const list=docs.slice(0,5);$('#document-list').innerHTML=list.length?list.map(row).join(''):'<div class="empty-state">No documents here yet. Add one to get started.</div>';let filtered=activeFilter==='All'?docs:docs.filter(d=>d.category===activeFilter);$('#alternate-list').innerHTML=filtered.length?filtered.map(row).join(''):'<div class="empty-state">No documents in this category yet.</div>';$('#todo-count').textContent=docs.filter(d=>d.statusType==='attention').length;$('#todo-total').textContent=docs.filter(d=>d.statusType==='attention').length;$('#doc-count').textContent=docs.length}
function showToast(msg){let t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),2600)}
function openDoc(id){let d=docs.find(x=>x.id===id)||initialDocs.find(x=>x.id===id);if(!d){showToast('This document is saved in your space.');return}currentDoc=d;$('#modal-title').textContent=d.title||d.name;$('#modal-intro').textContent=d.intro||'This document has been added to your Papertrail space. We’ll help surface the important details and dates.';$('#source-name').textContent=d.name;$('#source-quote').textContent=d.quote||'Papertrail has saved this document. Add a connected AI service to extract verified details and reminders.';$('#modal-next-text').textContent=d.next||'Open the document and review it when you have a moment.';$('#modal-category').textContent=`${d.category||'DOCUMENT'} · PAPERTRAIL FOUND THIS`;$('#modal-backdrop').classList.remove('hidden')}
function setView(view){const overview=view==='overview',profile=view==='profile';$('#overview-page').classList.toggle('hidden',!overview);$('#alternate-page').classList.toggle('hidden',overview||profile);$('#profile-page').classList.toggle('hidden',!profile);$$('.nav-item,.mobile-nav-item,.profile[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$('#crumb').textContent=overview?'Home':profile?'Your profile':view==='actions'?'To-dos':'Documents';if(!overview&&!profile){const actions=view==='actions';$('#alternate-title').textContent=actions?'To-dos':'Documents';$('#alternate-lede').textContent=actions?'Things to take care of, in one simple list.':'All your important files, together in one place.';$$('.alt-filters').forEach(e=>e.classList.toggle('hidden',actions));$('#alternate-list').innerHTML=actions?docs.filter(d=>d.statusType==='attention').map(row).join('')||'<div class="empty-state">You’re all caught up. Nice work.</div>':$('#alternate-list').innerHTML}window.scrollTo({top:0,behavior:'smooth'})}
document.addEventListener('click',e=>{const nav=e.target.closest('[data-view]');if(nav)setView(nav.dataset.view);const link=e.target.closest('[data-view-link]');if(link)setView(link.dataset.viewLink);const open=e.target.closest('[data-open]');if(open)openDoc(open.dataset.open);const cat=e.target.closest('[data-category]');if(cat){activeFilter=cat.dataset.category;setView('inbox');$$('.filter-chip').forEach(b=>b.classList.toggle('selected',b.dataset.filter===activeFilter));render()}const filter=e.target.closest('[data-filter]');if(filter){activeFilter=filter.dataset.filter;$$('.filter-chip').forEach(b=>b.classList.toggle('selected',b===filter));render()}});
$('#upload-btn').onclick=()=>$('#file-input').click();$('#upload-btn-alt').onclick=()=>$('#file-input').click();$('#file-input').addEventListener('change',e=>{const files=[...e.target.files];files.forEach(f=>{const ext=f.name.split('.').pop().toLowerCase();const doc={id:'upload-'+Date.now()+Math.random().toString(16).slice(2),name:f.name,detail:`Added just now · ${Math.max(1,Math.round(f.size/1024))} KB`,category:'Other',date:'Today',status:'Added',statusType:'ready',icon:ext==='pdf'?'PDF':ext.toUpperCase().slice(0,3),iconType:['jpg','jpeg','png'].includes(ext)?'image':'pdf'};docs.unshift(doc)});store();render();if(files.length)showToast(`${files.length} document${files.length===1?'':'s'} added to your space`);e.target.value=''});
$('#mobile-add').onclick=()=>$('#file-input').click();
const savedProfile=JSON.parse(localStorage.getItem('papertrail-profile')||'{}');
function showProfileName(name){$$('.profile-name').forEach(el=>el.textContent=name);$$('.profile-avatar,.profile-avatar-large').forEach(el=>el.textContent=name.trim().split(/\s+/).map(part=>part[0]).join('').slice(0,2).toUpperCase());const greeting=$('#overview-page h1');if(greeting)greeting.innerHTML=`Good morning, ${escapeHtml(name.split(/\s+/)[0])}<span class="wave">✳</span>`}
$('#profile-name-input').value=savedProfile.name||'Naomi Davis';$('#profile-email-input').value=savedProfile.email||'naomi@example.com';showProfileName($('#profile-name-input').value);
$('#profile-form').addEventListener('submit',e=>{e.preventDefault();const name=$('#profile-name-input').value.trim(),email=$('#profile-email-input').value.trim();if(!name||!email)return;localStorage.setItem('papertrail-profile',JSON.stringify({name,email}));showProfileName(name);showToast('Your profile has been saved.')});
['date-reminders','document-updates'].forEach(id=>{const input=$(`#${id}`);input.checked=localStorage.getItem(`papertrail-${id}`)!=='false';input.addEventListener('change',()=>{localStorage.setItem(`papertrail-${id}`,input.checked);showToast('Reminder settings saved.')})});
$('#modal-close').onclick=()=>$('#modal-backdrop').classList.add('hidden');$('#modal-backdrop').addEventListener('click',e=>{if(e.target.id==='modal-backdrop')e.currentTarget.classList.add('hidden')});document.addEventListener('keydown',e=>{if(e.key==='Escape')$('#modal-backdrop').classList.add('hidden')});$('#mark-done').onclick=()=>{if(currentDoc){const d=docs.find(x=>x.id===currentDoc.id);if(d){d.status='Handled';d.statusType='ready';store();render()}$('#modal-backdrop').classList.add('hidden');showToast('Marked as handled. One less thing to think about.')}};$('#ask-question').onclick=()=>showToast('Document chat is coming soon. Your source stays attached.');$('#help-btn').onclick=()=>showToast('Tell us what’s on your mind at hello@papertrail.app');$('#upgrade-btn').onclick=()=>showToast('Papertrail Plus is coming soon.');$('#filter-button').onclick=()=>setView('inbox');$('#search-open').onclick=()=>{const q=prompt('Search your documents');if(q!==null){setView('inbox');activeFilter='All';render();const matches=docs.filter(d=>d.name.toLowerCase().includes(q.toLowerCase()));$('#alternate-list').innerHTML=matches.length?matches.map(row).join(''):`<div class="empty-state">No documents found for “${escapeHtml(q)}”.</div>`}};
render();
if('serviceWorker' in navigator && (location.protocol==='https:'||location.hostname==='localhost'))navigator.serviceWorker.register('./service-worker.js').catch(()=>{});
